### ISSUE TITLE
Add more zone limits

### ISSUE THREAD

**Issue by LittleNightmare** [daemitus/YesAlready#10]
1. add zone limit to the folder, the priority could be individual > folder
2.  multiple zones support (I'm not sure it currently work or not)
3. not working in some zones e.g. only not work in Eurekan and Bozjan

**Comment by daemitus** [comment]
The same regex rules apply to zones currently.

Did you use the zone name from the prefill button, or just try to call it something like "Bozja"?

**Comment by LittleNightmare** [comment]
> Did you use the zone name from the prefill button, or just try to call it something like "Bozja"?

oh, just a typing problem. I hope could have a function that limits the trigger not work in some area but it looks like could use regex.

another thing is the first one. I didn't find an option to set zone limitations on the folder. I can set limits one by one, but I cannot set them to a folder.

**Comment by daemitus** [comment]
With the way  I've got the folders/items set up, especially with folders in
folders, it becomes a little hard to track what the parent is so as to
check the zone. Especially once you drag/drop the folder somewhere else.
Since generally you're apt to create the dialog when you see it, I would
just right click the folder you want it to go into, then right click the
new thing to autofill the zone. Slightly more hassle than setting it on a
folder, but it's not like you're going to be doing this all the time.

What is the dialog you're trying to use that you don't want to happen in
certain areas? Just trying to examine the use-case.
